In [112]:
import requests
import bs4
import pandas as pd
from bs4 import BeautifulSoup
import numpy as np 
url='https://geo.craigslist.org/iso/us'
 
res = requests.get(url)
res.raise_for_status()
soup = bs4.BeautifulSoup(res.text, 'html.parser')
 
# Collects all the cities in the US, with their associated CL site.
city_sites = dict()
for a in soup.find_all("a")[1:-7]:
    city = a.string
    if city not in city_sites:
        city_sites[city] = a.get('href')[8:-15]
        
cities = pd.DataFrame(list(city_sites.items()), columns = ['CITY', 'CRAIGSLIST_SITE'])

# Finds all the areas within that city.
def get_all_areas(site):
    response = requests.get(SITE_URL % site)
    response.raise_for_status()  # Something failed?
    soup = BeautifulSoup(response.content, 'html.parser')
    raw = soup.select('ul.sublinks li a')
    sites = {a.attrs['href'].rsplit('/')[1]: a.attrs['title'] for a in raw}
    return sites

SITE_URL = 'http://%s.craigslist.org'

## Actually carries out the scraping of sub-areas, city by city.
## I comment it out because it takes a long time to execute.
# areas = []
# for site in cities['CRAIGSLIST_SITE']:
#     area_list = get_all_areas(site)
#     if len(area_list) > 0:
#         areas.append(area_list)
#     else:
#         areas.append(np.nan)
#     print('{} > {}'.format(site, area_list))

cities['areas'] = areas
cities.to_csv('cities_and_areas.csv')

In [121]:
cities

,CITY,CRAIGSLIST_SITE,areas
0,"abilene, TX",abilene,NaN
1,akron / canton,akroncanton,NaN
2,"albany, GA",albanyga,NaN
3,"albany, NY",albany,NaN
4,albuquerque,albuquerque,NaN
5,altoona-johnstown,altoona,NaN
6,"amarillo, TX",amarillo,NaN
7,"ames, IA",ames,NaN
8,anchorage / mat-su,anchorage,NaN
9,"annapolis, MD",annapolis,NaN
10,"ann arbor, MI",annarbor,NaN
11,appleton-oshkosh-FDL,appleton,NaN
12,"asheville, NC",asheville,NaN
13,"ashtabula, OH",ashtabula,NaN
14,"athens, GA",athensga,NaN
15,"athens, OH",athensohio,NaN
16,"atlanta, GA",atlanta,"{'atl': 'atlanta', 'nat': 'otp north', 'eat': ..."
17,"auburn, AL",auburn,NaN
18,"augusta, GA",augusta,NaN
19,"austin, TX",austin,NaN
20,"bakersfield, CA",bakersfield,NaN
21,"baltimore, MD",baltimore,NaN
22,baton rouge,batonrouge,NaN
23,"battle creek, MI",battlecreek,NaN
24,beaumont / port arthur,beaumont,NaN
25,"bellingham, WA",bellingham,NaN
26,"bemidji, MN",bemidji,NaN
27,"bend, OR",bend,NaN
28,"billings, MT",billings,NaN
29,"binghamton, NY",binghamton,NaN
...,...,...,...
383,ventura county,ventura,NaN
384,vermont,vermont,NaN
385,"victoria, TX",victoriatx,NaN
386,visalia-tulare,visalia,NaN
387,"waco, TX",waco,NaN
388,"washington, DC",washingtondc,"{'doc': 'district of columbia', 'nva': 'northe..."
389,waterloo / cedar falls,waterloo,NaN
390,"watertown, NY",watertown,NaN
391,"wausau, WI",wausau,NaN
392,"wenatchee, WA",wenatchee,NaN
393,western IL,quincy,NaN
394,western KY,westky,NaN
395,western maryland,westmd,NaN
396,western massachusetts,westernmass,NaN
397,western slope,westslope,NaN
398,west virginia (old),wv,NaN
399,"wichita falls, TX",wichitafalls,NaN
400,"wichita, KS",wichita,NaN
401,"williamsport, PA",williamsport,NaN
402,"wilmington, NC",wilmington,NaN
403,"winchester, VA",winchester,NaN
404,"winston-salem, NC",winstonsalem,NaN
405,worcester / central MA,worcester,NaN
406,wyoming,wyoming,NaN
407,"yakima, WA",yakima,NaN
408,"york, PA",york,NaN
409,"youngstown, OH",youngstown,NaN
410,"yuba-sutter, CA",yubasutter,NaN
411,"yuma, AZ",yuma,NaN
412,zanesville / cambridge,zanesville,NaN